name: tModLoader Automatic Mod Browser Publish
author: Aaron Marais (@gear4s) - originally Javid Pack (@JavidPack)
description: Automatically build tModLoader Mod. Must execute on windows runner.

inputs:
    MODNAME:
        description: The internal name of the mod. Defaults to the repository name.
        required: false
        default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps: 
    - name: Build Mod
      shell: bash
      env:
        INPUT_MODNAME: ${{ inputs.MODNAME }}
      run: |
        if [ -z "$INPUT_MODNAME" ]; then
          echo "MODNAME Not provided, mod publish failure."
          exit
        fi
        echo INPUT_MODNAME is $INPUT_MODNAME
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
        echo CD to Home
        cd $HOME
        mkdir tModLoader
        cd tModLoader
        echo Downloading tModLoader
        curl -s -L https://github.com/tModLoader/tModLoader/releases/download/v0.11.8.8/tModLoader.Windows.v0.11.8.8.zip -o tModLoader.zip
        unzip -q tModLoader.zip
        echo Downloading ModCompile
        curl -s -L https://github.com/tModLoader/tModLoader/releases/download/v0.11.8.8/ModCompile_FNA.zip -o ModCompile.zip
        unzip -q ModCompile.zip -d ./ModCompile
        touch savehere.txt
        echo Installing XNA
        cp $GITHUB_ACTION_PATH/xnafx40_redist.msi .
        msiexec //i xnafx40_redist.msi //quiet
        echo XNA Installed
        mkdir -p ModLoader/Mod\ Sources/
        echo pwd is: ${PWD}
        echo ls -l is:
        ls -l
        echo Copy Workspace to correct foldername for build
        cp -r $GITHUB_WORKSPACE ModLoader/Mod\ Sources/$INPUT_MODNAME
        cd ModLoader/Mod\ Sources/$INPUT_MODNAME
        ls -l
        cd ../../..
        echo pwd is: ${PWD}
        echo Building Mod
        ls -l
        echo Initialize tModLoader.targets
        ./tModLoaderServer -build ModLoader/Mod\ Sources/$INPUT_MODNAME
        echo Build XNA dll
        cd ModLoader/Mod\ Sources/$INPUT_MODNAME
        dotnet restore
        C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe
        cd ../../..
        echo Build tmod file
        ./tModLoaderServer -build ModLoader/Mod\ Sources/$INPUT_MODNAME -eac ModLoader/Mod\ Sources/$INPUT_MODNAME/bin/Debug/net45/$INPUT_MODNAME.dll -unsafe false
        echo Done Building
        cd ModLoader/Mods
        ls -l

branding:
    icon: server
    color: blue
